del/q open-gto\account\*.gto
del/q open-gto\banned\*.gto
del/q open-gto\business\*.gto
del/q open-gto\config\*.gto
del/q open-gto\deathmatch\*.gto
del/q open-gto\deathmatch\record\*.gto
del/q open-gto\gang\*.gto
del/q open-gto\groundhold\*.gto
del/q open-gto\housing\*.gto
del/q open-gto\logging\player\*.log
del/q open-gto\logging\game\*.log
del/q open-gto\logging\debug\*.log
del/q open-gto\player\*.gto
del/q open-gto\race\*.gto
del/q open-gto\race\record\*.gto
del/q open-gto\weapon\*.gto