del/q Open-GTO\account\*.gto
del/q Open-GTO\banned\*.gto
del/q Open-GTO\business\*.gto
del/q Open-GTO\config\*.gto
del/q Open-GTO\deathmatch\*.gto
del/q Open-GTO\deathmatch\record\*.gto
del/q Open-GTO\gang\*.gto
del/q Open-GTO\groundhold\*.gto
del/q Open-GTO\housing\*.gto
del/q Open-GTO\logging\player\*.log
del/q Open-GTO\logging\game\*.log
del/q Open-GTO\logging\debug\*.log
del/q Open-GTO\player\*.gto
del/q Open-GTO\race\*.gto
del/q Open-GTO\race\record\*.gto
del/q Open-GTO\weapon\*.gto